### PR TITLE
Add response helpers

### PR DESCRIPTION
**Pull request by AngelMunoz**
I noticed that there were some Request helpers but no Response ones I believe these are good ones to include in the library as well, feel free to let me know if that is not the case

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
Good idea! Yes, this was because the library was written when fetch was only used for the client so the API wasn't used to create responses. Response helpers make sense if fetch API is used with bun.

Is it possible to test it? Right now the tests are running in node, but not sure if the polyfill allows for Response creation. If not, maybe include a usage sample in the README?

**Comment by AngelMunoz** [comment]
Sure! give me a couple of minutes

**Comment by AngelMunoz** [comment]
@alfonsogarciacaro I think that should be it, sadly the polyfill does not work for ArrayBuffer and Blob objects, but being able to use the string signature should be enough IMO

there's just an issue with one of the tests that for some reason keeps failing although I didn't touch it at all `fetch: request can be aborted`

**Comment by alfonsogarciacaro** [comment]
Thanks @AngelMunoz! I was trying to enable GH actions for the repo and apparently one test was failing because the error message was different on CI and locally but I could fix it. Now we have a nice green tick when merging the PRs :)

**Comment by AngelMunoz** [comment]
Hey @alfonsogarciacaro if you have any chance, can I bother you with a release in the next few days :)?

**Comment by alfonsogarciacaro** [comment]
Sure @AngelMunoz! I will be out for a few days so in case you need a release I've sent you an invitation to share ownership for the package. The README contains the instructions for publishing but they're the same as with other Fable repos :)

**Comment by alfonsogarciacaro** [comment]
~~Sorry, my bad, I forgot this package is currently published under Fable Nuget organization so I either need to change that or add you to Fable Nuget. I'll try to fix that.~~

My bad again 😅  if you don't have a FABLE_NUGET_KEY it should default to NUGET_KEY so in principle should work as is. Please give it a try.

**Pull request merged**
